services:
  mongo:
    image: mongo:6.0
    container_name: ai_claims_assessment_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: ai_claims_assessment_api
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["go", "run", "main.go"]

volumes:
  mongo_data:
